name: Build & Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      #  Check modeler
      - name: Install dependencies
        run: npm ci

      - name: Setup puppeteer/chrome apparmor profile
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          cat | sudo tee /etc/apparmor.d/chrome-puppeteer <<EOF
          abi <abi/4.0>,
          include <tunables/global>

          profile chrome /@{HOME}/.cache/puppeteer/chrome/*/chrome-linux64/chrome flags=(unconfined) {
            userns,

            include if exists <local/chrome>
          }
          EOF
          sudo service apparmor reload

      - name: Test & Lint library
        if: matrix.os == 'ubuntu-latest'
        env:
          TEST_BROWSERS: ChromeHeadless,Firefox
        run: xvfb-run npm run all

      - name: Build modeler
        if: matrix.os != 'ubuntu-latest'
        env:
          TEST_BROWSERS: ChromeHeadless
        run: npm run all

      - name: Setup and build starter
        working-directory: ./starter
        run: |
          npm install
          npm run all
